config/routes.rb
Rails.application.routes.draw do
  resources :employees, only: [:index] do
    collection do
      post :import
    end
  end


  root 'welcome#index'

  get 'welcome/upload'
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	require 'csv'

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|

      employee_hash = row.to_hash # exclude the price field
      employees = Employee.where( name: employee_hash["name"], number: employee_hash["number"])

      if employees.count > 1
        employees.first.update_attributes(employee_hash)
      else
        Employee.create!(employee_hash)
      end # end if !employee.nil?
    end # end CSV.foreach
  end # end self.import(file)
end # end class

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
    unless params[:name].to_s.empty?
      @employees = @employees.where("name like ?", "%#{params[:name]}%")
    end
    unless params[:date].to_s.empty?
      @employees = @employees.where("date like ?", "%#{params[:date]}%")
    end
    unless params[:number].to_s.empty?
      @employees = @employees.where(number: params[:number])
    end
    respond_to do |format|
      format.json { render json: @employees}
    end
  end

  def import
    Employee.import(params[:file])
    respond_to do |format|
      format.html { redirect_to root_url, notice: "Employees imported." }
      format.json { render json: Employee.all}
    end

  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def upload
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"
    title EmployeeTest
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    = yield

app/views/welcome/index.html.slim
h1 Sentia Sample Project
h2 Part 1
p
  | In this part, use
  span<> = link_to 'this CSV', 'test.csv'
  | file to take the data in, and save it to the database.
h3 Checklist
ul
  li Create model to store data
  li Upload CSV via AJAX form
  li Save to database
  li Display success/error message

h2 Part 2
p
  | Use the data and model created in part 1 to create a table that displays the data
  br
  | An AJAX form should be used to filter the data

h3 Checklist
ul
  li Create table to display data
  li Create AJAX form to filter data
  ul
    li Filter on the date column
    li Filter on the name column
    li Filter on the number column
  li Display a filter updated message

a.btn.btn-success.navbar-btn.btn-sm href="/welcome/upload"  Please Click Here to view Demo

app/views/welcome/upload.html.slim
h1 Upload CSV
div#message
hr
== form_tag import_employees_path(format: :json), method: :post, remote: true, multipart: true, id: 'upload_form'
  div
    == file_field_tag :file
  div
    == submit_tag  'Import'

hr
== form_tag employees_path, method: :get, id: 'filter_form' do
  div
    == label_tag :name
    == text_field_tag :name
  div
    == label_tag :date
    == text_field_tag :date
  div
    == label_tag :number
    == text_field_tag :number
  div
    == submit_tag 'Filter'

hr
table#table
  thead
    tr
      th Name
      th Date
      th Number
      th Description
  tbody